name: Sync to theyrealtyteam

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Debug PAT
        run: echo "PAT length: ${#TARGET_REPO_PAT}"
        env:
          TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}

      - name: Push to target repository
        env:
          TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote add target https://x-access-token:$TARGET_REPO_PAT@github.com/TheYRealtyTeam/theyrealtyteam.git
          git push --force target main:main
